patch_encoder_preset: "dinov2l16_384"
image_encoder_preset: "dinov2l16_384"
checkpoint_uri: "source/predictor/checkpoints/depth_pro.pt"
decoder_features: 256
use_fov_head: true
fov_encoder_preset: "dinov2l16_384"